:- dynamic roomType/2, roomCenter/3.
roomType(toilet,toilet).
roomCenter(toilet,87,14).
roomType(secondaryCorridor,corridor).
roomCenter(secondaryCorridor,79,30).
roomType(lavatory,lavatory).
roomCenter(lavatory,82,33).
roomType(serviceRoom,room).
roomCenter(serviceRoom,84,37).
roomType(corridor,corridor).
roomCenter(corridor,42,47).
roomType(printerRoom,room).
roomCenter(printerRoom,84,48).
roomType(nardiOffice,office).
roomCenter(nardiOffice,46,61).
roomType(phdRoom,room).
roomCenter(phdRoom,80,59).
roomType(cis,cis).
roomCenter(cis,13,62).
roomType(quaglia,quaglia).
roomCenter(quaglia,37,62).
roomType(matthewOffice,office).
roomCenter(matthewOffice,54,62).
